import time
import requests
import re
import datetime
import os
import cx_Oracle


def get_html(url,data):
   data = data
   url = url
   headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'}
   html = requests.post(url=url, headers=headers, data=data).text
   return html

def re_html(data):
    str1 = (re.search(r'series: \[(.*?)\t\].*?', data, re.M | re.S).group().strip())
    result = re.findall(r'data: (.*?)\}', str1)
    return result


def listToOracle(carList):
   try:
        conn = cx_Oracle.connect('scott/scott@192.168.122.1/orcl')
        # dsn_tns = cx_Oracle.makedsn('192.168.121.1', '1521', service_name='orcl')
        # conn = cx_Oracle.connect(user='scott', password='scott', dsn=dsn_tns)
        cur = conn.cursor()
        cur.executemany("insert into scott.T_DEV_OPERATION_RATE(PL_ID,MODULE_NUM,PRODUCT,WAIT_PREVIOUS,WAIT_NEXT,CHANGEOVER,PART_SUPPLY,MACHINE_ERROR,OPERATOR_DOWNTIME,MAINTENANCE,OTHER,SPIDER_TIME) values(:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12)",carList)
        conn.commit()
        cur.close()
        conn.close()
   except Exception as e:
        return e


def logging(strLog):
    if os.path.exists("./utilization.log"):
        fsize = os.path.getsize("./utilization.log") / float(1024 * 1024)
        if fsize >= 0.02:
            os.rename("./utilization.log","./utilization"+"_"+datetime.datetime.strftime(datetime.datetime.now(),'%Y-%m-%d_%H%M%S')+".log")
            f = open("./utilization.log", "w+")
        else:
            f = open("./utilization.log", "a+")
    else:
        f = open("./utilization.log", "w+")
    f.write(str(datetime.datetime.now()) + "  "+strLog+'\n')
    f.close()

curr_time = datetime.datetime.now()
start=str((curr_time-datetime.timedelta(hours=1)).strftime("%Y-%m-%d %H"))+':00'
end=str(datetime.datetime.strftime(curr_time,'%Y-%m-%d %H'))+':00'

data2_stronger = {
  "__EVENTTARGET": "",
  "__EVENTARGUMENT": "",
  "__VIEWSTATE": "/wEPDwUJNzkyNzQzMzk2D2QWAmYPZBYaAgEPZBYEZg8PFgIeBFRleHQFD1Byb2R1Y3Rpb24gZGF0YWRkAgMPDxYGHwAFEHdvcmtpbmcgb24gRmxleGEeCENzc0NsYXNzBQlXaGl0ZVRleHQeBF8hU0ICAmRkAgMPZBYGZg9kFhBmD2QWAmYPZBYEZg8PFgIfAAUHTG9nIG9mZmRkAgEPDxYCHgdUb29sVGlwBSpDbGljayB0aGlzIGJ1dHRvbiB0byBtaW5pbWl6ZSB0aGUgc2lkZWJhci5kZAIDD2QWAmYPZBYCZg8PFgIfAAUNRmxvb3IgTW9uaXRvcmRkAgQPZBYCZg9kFgJmDw8WBB8ABQhXYXJuaW5ncx4HVmlzaWJsZWhkZAIFD2QWAmYPZBYCZg8PFgIfAAUMRXJyb3IgU2VhcmNoZGQCBg9kFgJmD2QWAmYPDxYCHwAFLkF1dG8gQ2hhbmdlb3Zlcjxicj4mbmJzcDsmbmJzcDsoSGFuZHkgU2Nhbm5lcilkZAIMD2QWAmYPZBYCZg8PFgQfAAUPU3lzdGVtIFNldHRpbmdzHwRnZGQCDQ9kFgJmD2QWAmYPDxYCHwAFEFN0YXR1cyBSZWZlcmVuY2VkZAIRD2QWAmYPZBYCAgEPFgIeC18hSXRlbUNvdW50ZmQCAQ8WAh8EaBYCZg9kFgJmD2QWAmYPDxYCHwMFKUNsaWNrIHRoaXMgYnV0dG9uIHRvIHJlc3RvcmUgdGhlIHNpZGViYXIuZGQCAg8WAh8EaGQCBQ8PFgIfAAULQTAxLTEwLUxpbmVkZAIHDw9kFgIeBXN0eWxlBSVtYXJnaW4tbGVmdDoyOTBweDt2aXNpYmlsaXR5OnZpc2libGU7FgxmDw8WAh4ISW1hZ2VVcmwFC2ltZy9yZXcucG5nZGQCAg8PZBYCHwYFEnZpc2liaWxpdHk6aGlkZGVuO2QCAw8PFgIfBwUPaW1nL2ZvcndhcmQucG5nFgIfBgUSdmlzaWJpbGl0eTpoaWRkZW47ZAIEDw8WAh8HBaYMZGF0YTppbWFnZS9wbmc7YmFzZTY0LGlWQk9SdzBLR2dvQUFBQU5TVWhFVWdBQUFDQUFBQUFnQ0FZQUFBQnplbnIwQUFBQUFYTlNSMElBcnM0YzZRQUFBQVJuUVUxQkFBQ3hqd3Y4WVFVQUFBQUpjRWhaY3dBQURzTUFBQTdEQWNkdnFHUUFBQVFnU1VSQlZGaEh6VlpiVDFSWEZON0R6QUJUNG1WR3NZcUNGd3JETU5vcUpVV1VvbW1Dc2ZGQlgwaWJORkVlMnFhUHB2R1JKeFd0VlVhTHRtblRtNjNhbGpacVVzeVVOb09Ua2ttQWxJUk1EUEV2d0F0UDNHOWY5N2RsSC9lY21UTU10a1JQc3VhY3RmYTN2dld0dGZlY0dTRnNWeVFTZ1duMjlaWDQ4WGk4ME1ZM2s1Ny9wdmhJTklpb3NrYlJQVFkyQnRNWWUxYnpOZm4rTXJsR1JrY1dMQzdXWTIxeFVEejBYUGJBM2U2RzU0SWJ3OFBES2JiLzFtNGM3MjdFZXoxSDhFSGlCRTcvOHc1YWs2ZHcvdkdITUs4MjZiY21XeFNHV09ZMGRlNVA0UnA2TklTQ1MxNTRJeDU0MmoxZ2JTVkFmQ0lnTGt0ckVlam82RWd4ZDNNZTluWnVRZjI5TXJ6MW9CekgvcXhDYzN3UFRpWnFVZ1RRWjV3WVlwbmplNzhnaFN0eUxRSlhzd3VlU0I3RUZWbFBDV2dRY1NYZ1U0RzhNeTZFNmtNSTFZVlFYUnZDN3Zvd1Nsclg0TlZmTnVPTnU5dHc2UGVkT1BwSEpVN0V3aW5GNmJ6Nzkyc3FUZ3l4ek5uUkZrRDRRRFhDUzN5aHVpcmtmK3lHbXdMWU1HdXJqNHZTdVNRRnRMdFErSmtIYTI4VW9QakxJcFIrdXc2di9MQUI0WjllUnMydkpUaHdmN3ZxOE8zdVlKcUE0N0ZxRlNlR1dPWXdseHprSWllNWFhekRocDhLdUNBZFRrR09KZitxRzBYWDh4SDR3b2N0WDYvQmp1LzlDTjdhaUQwL2IwYnRiMXRWQVgwZDdhNjBucHVpRlRqY3RVdGhpR1VPYzhsQkxuS1N1L0NhOThuNFpjT3BBaWhDcW5KSFhQQVpVOWo2elZyc3ZPbEgxZTFpUmN6dW5LNjZ1NlVLUXl4em1LdTdKeWU1Q3lpQTNiTmhhd3ZPUzZmdDZSUzhWL1B3VW9jWDZ6NHZSUEZYUllxSWhKV3lxK283bTlUKzd1c3N3ZXVHR1BxTUUyTVZsN25rSUJjNVZlYzBGdWUyV3dMT1NlZXNORTVCanNhbHQwS0xrSHRZSWtkWjl0MTY3TG9aUU1XUEcxU1hJU21HZ25pbnp6Z3h4TEp6RmkrU0hCdzlPZFhZYWF6RGhwVUFJUTR0TGk1aVlXRWhaNXVmbjBjbVd3a0hhN0wyTXd1WW01dURhUlNVcXdDTnRRUXcwYW1yVEhGN2NlMnZoSU0xWHl3QlRsM3B1RlJMeFNsanQrZG9UQzdZdEFrNENjaVYxRjUwT1JFWkJjek96c0xKTktGZU53WGIxelRHS2M1MW5oZnJETkRKVnB4cnoxWEF6TXlNSllEUHRFd1QwR3Y2cmtYYjQvVFRKcEFKWk1ic1pFNEhNSmZpcXlMQW5KSVdPejA5RFNkakE5WVpvSk1OekRXVDFMNEZTMlFLbzNtV0UvRy9DakNMVFUxTlFadU9tekg5bkNZZ0U4aUpqRjFtT29SMmpoZEt3T1RrSkV4YittbzNxbDlET25hQTNkZmRNTzQwZ1d3NXF5ckFQSVM2a0NtWXNXUXlpV2cwaXA2ZUhnd01ES0MzdDNkRVl0WmJFNWlZbUVBMjA0VEVjSy90N3dIRzdMOGJKbDlYVnhmNEo0UmkrdnY3Si94K2Z4bUw1eXpBSkhNU2tLMkJXQ3lHOGZGeERBNE9UcGVYbDlmbzRydzM4bnZOeFZ4TlQ4RTg5WXhseSsvcjYrUG9KNFBCWUsxWlhBbmdlM201Vi9GL1hVOGtFcU9CUUNCa0wwNi9WTnJCSld1UTk5VXc4bS9MVlB4ZndWampvSDJPRW1NQUFBQUFTVVZPUks1Q1lJST1kZAIFDw8WAh8HBa4MZGF0YTppbWFnZS9wbmc7YmFzZTY0LGlWQk9SdzBLR2dvQUFBQU5TVWhFVWdBQUFDQUFBQUFnQ0FZQUFBQnplbnIwQUFBQUFYTlNSMElBcnM0YzZRQUFBQVJuUVUxQkFBQ3hqd3Y4WVFVQUFBQUpjRWhaY3dBQURzTUFBQTdEQWNkdnFHUUFBQVFsU1VSQlZGaEh6VlpaYjFOSEZCN0hkaElUc2RnMExJR2tRRW9jeHl4dEdqVUUwbEFoQllGNGdKZW9sU29CRDdUcVkxWHhtQ2NndEVCamFMcW9WVGRhdXFVVklEV1ZDY2lwMWNoU0VqVVNzcXFJdnhCZThwUjkrNWh2eUZ6R1k5L2dzSlVySFYrZk05LzV6bmZPekwyMkVOWVZpOFZnbXIyK0ZEK1pUQlpiZkZQWithK0w5MFNqaUN0ckV0MGpJeU13amJGSHRVQno0SmJKTlh4M2VNN2hZajNXRm52RTM3NExQbmpidmZDZDlXSm9hQ2pEZGwzWmhzUGRUWGk3WnovZVNSM0IrLysraWRiME1aeTU4eTdNcTAzNnJlbmpDa01zYzVvN2QyVnczZjd2Tm9yTytlR1ArZUJyOTRHMWxRRHhrWUM0SU8yNFFFZEhSNFo1V3dyd2N1ZDZORnlyd0w2L0tuSG9aalZha3R0eE5GV2JJWUErNDhRUXk1ekFpYUlNcnRpbEdEd3RIdmhpQlJBZnkzcEtRS05JS2dIbkJRcE9laEJwaUNCU0gwRk5YUVRiR3FJb2ExMk9IYit0dzJ0WE4yTHZuNXR4NEVZVmppU2lHY1hwdlBYUFRoVW5obGptYkdvTElicTdCdEVGdmtoOU5Rby84TUpMQVd5WXRkWEhoOUk1SndXMGUxRDhpUThyUGl0QzZaY2xLUDkySlY3NllUV2l2NnhGN2U5bDJIMzlSZFhod2U1d2xvRERpUm9WSjRaWTVqQ1hIT1FpSjdscHJNT0dId2c0S3gxT1FZNmw4S0lYSlo4V0l2UkZBT3UvWG81TjN3Y1J2dklDdHYrNkRuVi9iRkFGOUhXZ3U4cjUzaHpmaWplNnRpZ01zY3hoTGpuSVJVNXlGMS95M3grL2JEaFRBRVZJVmQ2WUJ3RmpDaHUrV1lITmw0T28vcWxVRWJNN3Q2dithcm5DRU1zYzV1cnV5VW51SWdwZzkyelkyWUl6MG1sN01BWC94UUlzNi9CajVlZkZLUDJxUkJHUnNFcDJWZlB6R3JXL3IzU1c0VlZEREgzR2lYR0t5MXh5a0l1Y3FuTWFpM1BiSFFHbnBYTktHcWNnUitQUlc2RkZ5RDBzazZPcytHNFZ0bHdPWWV1UHExV1hFU21HZ25pbnp6Z3h4TEp6RmkrUkhCdzlPZFhZYWF6RGhwVUFJZmJPejg5amJtNHViNXVkblVVdVd3b0hhN0wySXd1WW1abUJhUlNVcndDTmRRUXcwYTJyWEhHN3VQYVh3c0dhejVjQXQ2NTBYS3FsNG95eDJ6a2FrdzgyYXdKdUF2SWx0WXMrVEVST0FkUFQwM0F6VGFqWFRjSDJtc2E0eGJuTzgrS2NBVHFMRmVmYS95cGdhbXJLRWNEdnRGd1QwR3Y2cmtYYmNmcFpFOGdGTW1NMjJYTXBZSEp5RXFacDBYYWNQaHR3emdDZFhDQTNNbnNMRnNqVU51a2M4K2w1SmdMTWMySS91aE1URTdBdGF3SzVRR1pNa3pLbVIyaWVBOFpzRGpQbnFRcHdLMlRHeDhmSFlkckNvOTJrZmczcDJBRGIxMlNNMnhNdzE4dzh0emd4VDFTQWVRaTFBTHQ0T3AxR1BCNUhUMDhQQmdZRzBOdmJPeXd4cTV3SmpJMk5ZVEhUaE1Sd1ArM2ZEc2JzdzJmeWRYVjFnWDlDS0xDL3YzOHNHQXhXc0hqZUFrd3lOd0dMTlpCSUpEQTZPb3JCd2NISnlzcktXbDJjOXlZK1Fsek0xL1FVekpQTjJHTDVmWDE5SFAxNE9CeXVNNHNyQVh3dlAreFYvTGpycVZUcWJpZ1VpdGpGNlpkTDI3TmdqZkwrTkl6OEczTVZ2d2Q5enVERXhLQ0ZkQUFBQUFCSlJVNUVya0pnZ2c9PWRkAgYPD2QWAh8GBRJ2aXNpYmlsaXR5OmhpZGRlbjtkAgkPDxYEHglCYWNrQ29sb3IKpAEfAgIIZGQCCw8PFgQfCApFHwICCGRkAg0PDxYEHwgKpAEfAgIIZGQCDw8PFgQfCAqkAR8CAghkZAIRDw8WBB8ICqQBHwICCGRkAhMPDxYEHwgKpAEfAgIIZGQCFQ8PFgQfCAqkAR8CAghkZAIZDw8WBB8ICqQBHwICCGRkAhsPZBYEZg9kFgQCBA8WAh8FAgUWCgIBD2QWGgIBDw8WAh8ABQtBMDEtMTAtTGluZWRkAgMPDxYCHwAFAk0xZGQCBA8VAUZUaGUgam9iIG5hbWUgaXMgQ09QWS1NNS0yMDQwMDAyMTA1NzEtMTAuMS1GaXN0IEwgRlBDLVQwMSg4KzgpX1RGaXN0IEwuZAIFDw8WAh8ABQMwLjBkZAIGDxUBRlRoZSBqb2IgbmFtZSBpcyBDT1BZLU01LTIwNDAwMDIxMDU3MS0xMC4xLUZpc3QgTCBGUEMtVDAxKDgrOClfVEZpc3QgTC5kAgcPDxYCHwAFAzAuMGRkAggPFQFGVGhlIGpvYiBuYW1lIGlzIENPUFktTTUtMjA0MDAwMjEwNTcxLTEwLjEtRmlzdCBMIEZQQy1UMDEoOCs4KV9URmlzdCBMLmQCCQ8PFgIfAAUDMC4wZGQCCg8VAUZUaGUgam9iIG5hbWUgaXMgQ09QWS1NNS0yMDQwMDAyMTA1NzEtMTAuMS1GaXN0IEwgRlBDLVQwMSg4KzgpX1RGaXN0IEwuZAILDw8WAh8ABQMwLjBkZAIMDxUBRlRoZSBqb2IgbmFtZSBpcyBDT1BZLU01LTIwNDAwMDIxMDU3MS0xMC4xLUZpc3QgTCBGUEMtVDAxKDgrOClfVEZpc3QgTC5kAg0PDxYCHwAFAzAuMGRkAg8PDxYCHwBlZGQCAg9kFhoCAQ8PFgIfAGVkZAIDDw8WAh8ABQJNMmRkAgQPFQFGVGhlIGpvYiBuYW1lIGlzIENPUFktTTUtMjA0MDAwMjEwNTcxLTEwLjEtRmlzdCBMIEZQQy1UMDEoOCs4KV9URmlzdCBMLmQCBQ8PFgIfAAUDNC4xZGQCBg8VAUZUaGUgam9iIG5hbWUgaXMgQ09QWS1NNS0yMDQwMDAyMTA1NzEtMTAuMS1GaXN0IEwgRlBDLVQwMSg4KzgpX1RGaXN0IEwuZAIHDw8WAh8ABQM0LjFkZAIIDxUBRlRoZSBqb2IgbmFtZSBpcyBDT1BZLU01LTIwNDAwMDIxMDU3MS0xMC4xLUZpc3QgTCBGUEMtVDAxKDgrOClfVEZpc3QgTC5kAgkPDxYCHwAFAzQuMWRkAgoPFQFGVGhlIGpvYiBuYW1lIGlzIENPUFktTTUtMjA0MDAwMjEwNTcxLTEwLjEtRmlzdCBMIEZQQy1UMDEoOCs4KV9URmlzdCBMLmQCCw8PFgIfAAUDNC4wZGQCDA8VAUZUaGUgam9iIG5hbWUgaXMgQ09QWS1NNS0yMDQwMDAyMTA1NzEtMTAuMS1GaXN0IEwgRlBDLVQwMSg4KzgpX1RGaXN0IEwuZAINDw8WAh8ABQM0LjBkZAIPDw8WAh8AZWRkAgMPZBYaAgEPDxYCHwBlZGQCAw8PFgIfAAUCTTNkZAIEDxUBRlRoZSBqb2IgbmFtZSBpcyBDT1BZLU01LTIwNDAwMDIxMDU3MS0xMC4xLUZpc3QgTCBGUEMtVDAxKDgrOClfVEZpc3QgTC5kAgUPDxYCHwAFAzUuMWRkAgYPFQFGVGhlIGpvYiBuYW1lIGlzIENPUFktTTUtMjA0MDAwMjEwNTcxLTEwLjEtRmlzdCBMIEZQQy1UMDEoOCs4KV9URmlzdCBMLmQCBw8PFgIfAAUDNS4wZGQCCA8VAUZUaGUgam9iIG5hbWUgaXMgQ09QWS1NNS0yMDQwMDAyMTA1NzEtMTAuMS1GaXN0IEwgRlBDLVQwMSg4KzgpX1RGaXN0IEwuZAIJDw8WAh8ABQM1LjJkZAIKDxUBRlRoZSBqb2IgbmFtZSBpcyBDT1BZLU01LTIwNDAwMDIxMDU3MS0xMC4xLUZpc3QgTCBGUEMtVDAxKDgrOClfVEZpc3QgTC5kAgsPDxYCHwAFAzUuMGRkAgwPFQFGVGhlIGpvYiBuYW1lIGlzIENPUFktTTUtMjA0MDAwMjEwNTcxLTEwLjEtRmlzdCBMIEZQQy1UMDEoOCs4KV9URmlzdCBMLmQCDQ8PFgIfAAUDNS4xZGQCDw8PFgIfAGVkZAIED2QWGgIBDw8WAh8AZWRkAgMPDxYCHwAFAk00ZGQCBA8VAUZUaGUgam9iIG5hbWUgaXMgQ09QWS1NNS0yMDQwMDAyMTA1NzEtMTAuMS1GaXN0IEwgRlBDLVQwMSg4KzgpX1RGaXN0IEwuZAIFDw8WAh8ABQMzLjlkZAIGDxUBRlRoZSBqb2IgbmFtZSBpcyBDT1BZLU01LTIwNDAwMDIxMDU3MS0xMC4xLUZpc3QgTCBGUEMtVDAxKDgrOClfVEZpc3QgTC5kAgcPDxYCHwAFAzQuMWRkAggPFQFGVGhlIGpvYiBuYW1lIGlzIENPUFktTTUtMjA0MDAwMjEwNTcxLTEwLjEtRmlzdCBMIEZQQy1UMDEoOCs4KV9URmlzdCBMLmQCCQ8PFgIfAAUDNC4wZGQCCg8VAUZUaGUgam9iIG5hbWUgaXMgQ09QWS1NNS0yMDQwMDAyMTA1NzEtMTAuMS1GaXN0IEwgRlBDLVQwMSg4KzgpX1RGaXN0IEwuZAILDw8WAh8ABQM0LjFkZAIMDxUBRlRoZSBqb2IgbmFtZSBpcyBDT1BZLU01LTIwNDAwMDIxMDU3MS0xMC4xLUZpc3QgTCBGUEMtVDAxKDgrOClfVEZpc3QgTC5kAg0PDxYCHwAFAzQuMWRkAg8PDxYCHwBlZGQCBQ9kFhoCAQ8PFgIfAGVkZAIDDw8WAh8ABQJNNWRkAgQPFQFGVGhlIGpvYiBuYW1lIGlzIENPUFktTTUtMjA0MDAwMjEwNTcxLTEwLjEtRmlzdCBMIEZQQy1UMDEoOCs4KV9URmlzdCBMLmQCBQ8PFgIfAAUEMjEuMGRkAgYPFQFGVGhlIGpvYiBuYW1lIGlzIENPUFktTTUtMjA0MDAwMjEwNTcxLTEwLjEtRmlzdCBMIEZQQy1UMDEoOCs4KV9URmlzdCBMLmQCBw8PFgIfAAUEMjEuMGRkAggPFQFGVGhlIGpvYiBuYW1lIGlzIENPUFktTTUtMjA0MDAwMjEwNTcxLTEwLjEtRmlzdCBMIEZQQy1UMDEoOCs4KV9URmlzdCBMLmQCCQ8PFgIfAAUEMjEuMGRkAgoPFQFGVGhlIGpvYiBuYW1lIGlzIENPUFktTTUtMjA0MDAwMjEwNTcxLTEwLjEtRmlzdCBMIEZQQy1UMDEoOCs4KV9URmlzdCBMLmQCCw8PFgIfAAUdPGZvbnQgY29sb3I9J3JlZCc+MjEuMDwvZm9udD5kZAIMDxUBRlRoZSBqb2IgbmFtZSBpcyBDT1BZLU01LTIwNDAwMDIxMDU3MS0xMC4xLUZpc3QgTCBGUEMtVDAxKDgrOClfVEZpc3QgTC5kAg0PDxYCHwAFBDIxLjBkZAIPDw8WAh8AZWRkAgYPDxYCHwAF5QJOb3RlOiBFYWNoIHZhbHVlIGluZGljYXRlcyB0aGUgcHJvZHVjdGlvbiB0aW1lIGZyb20gaW1tZWRpYXRlbHkgYmVmb3JlIHRoZSBmaXJzdCBzZXF1ZW5jZSB1bnRpbCBpbW1lZGlhdGVseSBhZnRlciB0aGUgZmluYWwgc2VxdWVuY2UuIDxicj5Mb2NhdGUgdGhlIGN1cnNvciBvdmVyIDxmb250IGNvbG9yPSJncmVlbiI+KjwvZm9udD4gdG8gZGlzcGxheSBkZXRhaWxzIG9uIG5vbi1wcm9kdWN0aW9uIHRpbWVzIHN1Y2ggcmVjb3ZlcmllcyBhbmQgcHJvZHVjdGlvbiBzdG9wIGNhdXNlcy4gVGhpcyBub24tcHJvZHVjdGlvbiB0aW1lIGlzIG5vdCBpbmNsdWRlZCBpbiB0aGUgZGlzcGxheWVkIHRvdGFsIHByb2R1Y3Rpb24gdGltZS5kZAIED2QWAmYPZBYCZg9kFgJmD2QWAgIEDxAPFgIeB0NoZWNrZWRoZGRkZBgCBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WFgUSVWNIZWFkZXIxJGliU2VhcmNoBRdVY01lbnUkSW1hZ2VCdXR0b25DbG9zZQUPSW1hZ2VCdXR0b25CYWNrBRNJbWFnZUJ1dHRvbkJhY2tIYWxmBRZJbWFnZUJ1dHRvbkZvcndhcmRIYWxmBRJJbWFnZUJ1dHRvbkZvcndhcmQFGkltYWdlQnV0dG9uVXBkYXRlWWVzdGVyZGF5BRZJbWFnZUJ1dHRvblVwZGF0ZVRvZGF5BRZJbWFnZUJ1dHRvblVwZGF0ZVNoaWZ0BRRJbWFnZUJ1dHRvblVwZGF0ZTEyMAUTSW1hZ2VCdXR0b25VcGRhdGU2MAUTSW1hZ2VCdXR0b25VcGRhdGUzMAURSW1hZ2VCdXR0b25VcGRhdGUFD0ltYWdlQnV0dG9uVGFjdAUVSW1hZ2VCdXR0b25Qcm9kdWN0aW9uBRJJbWFnZUJ1dHRvbkhpc3RvcnkFEUltYWdlQnV0dG9uUGFuZWxzBRRJbWFnZUJ1dHRvblBhcnRVc2FnZQUWSW1hZ2VCdXR0b25JbmZvcm1hdGlvbgUTSW1hZ2VCdXR0b25FdmVudExvZwURTGlua0J1dHRvblJlZnJlc2gFEkltYWdlQnV0dG9uRWFjaEpvYgUKTXVsdGlWaWV3MQ8PZAIBZLRYKeXQwKlUXveoPdCnPXsWakMZE/n1z13hIhlcPzYk",
  "__EVENTVALIDATION": "/wEdACHVu6XRAn6TkCRrbT84nkRj0J4eK2Fe6yzl9vedxHqyhLh6jHhWtGy+v7iWhTtOE7Qyn9o1AWpGrMI48F2UWCsGbDpLkBvxhhgNkpQKEpKrdBGcovCeb7vQjSVDhBRTQvps0iAst08a0rHslo5zV/nu9Lv7ve9EysSO6VGXmHqDBe3+MR9ycrSqOKmhQJXtO3GfBqBksFSnsAVOMH/NfLz22/YgBXLOKUJOTZm/BnynJUV3jyXV/eH2jUu6avXmp8qqi8lkH3yyLR/Ew6I3miarPRHrsX+lS07KJ1l4lNkdVqwuTrZMkXBDa297nQKB2z5ymXNje9mGByZvlbKcO/aooTOPQTroCVYNu8NKYvXNY+qJdhA+DIe2XOHtlPq2tEr2w7PZv7mAnwL9RAjhwEBYJANa5dd5BhD7EIzCFz2ZaZJ53ZgM9ZoWfWb2mVmHVvlkOQur+3IN59rnKcJvPTeRIRFDHRrZ66YaQH6vPIIRn+iaowRwWBFaNjleg3gxzihQsSuYOIiQ0iF63EtYAfgenRVa40+P14x1f8DN1lnYwVmKUI1pAIfCfnxZRVr1Z9f2gesWkeYaWW2z6rabKf2rQVFZ7fa+Th6amA3bAvgkwHgA71oqwflYo6X+cNISNKJK+0EyzSJyYkXnfH4e9X553YPNAxyjo3UatNIe5d8cNYF/Jafn3TRJLuihf7boAbL6Hn2mLK2+qT6zocC5m5SVN2aILd2srWxewGYBpqzwPw==",
  "UcHeader1$tbSearch": "",
  "dtPickerFrom": start,
  "dtPickerTo": end,
  "ImageButtonUpdate.x": "20",
  "ImageButtonUpdate.y": "11",
}

urlDict_GD2_stronger={
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-5-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-6-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-7-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-8-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-9-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-10-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-11-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-12-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-13-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-14-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-15-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-16-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-17-Line',
    'http://10.10.33.134/fujiweb/fujimoni/UI/TactInfo.aspx?Line=A01-20-Line',
}

carList=[]
for url in urlDict_GD2_stronger:
    html = get_html(url, data2_stronger)
    r=re_html(html)
    line=url[(url.rfind('=')+1):]
    fList=[]
    fList.append(line)
    fList.append((len(r[0].split(","))))
    if len(r) == 9:
        for e in r:
            aa = e[1:-1]
            templist = aa.split(',')
            flist=list(map(int, templist))
            final=sum(flist)
            fList.append(final)
        fList.append(end)
        print(fList)
        logging(end + " "+ line + " 获取数据OK")
        carList.append(fList)
        time.sleep(0)
    else:
        logging(end+" "+line+" 获取数据错误")

# e=listToOracle(carList)
# logging(end+" "+" 数据库报错信息:"+str(e))